### ISSUE TITLE
Missing meeting updates and youtube links

### ISSUE THREAD

**Issue by okwme** [interNFT/documentation#22]
The meetings page hasn't been updated with slides or relevant [youtube videos](https://www.youtube.com/channel/UCEmFhwNH8AiHR8dNSZ9fB0w/videos). There's no designation between the NFT group and the Metadata subgroup either. There are 9 videos but only reference to 6 calls on the website.

**Comment by jandrieu** [comment]
@ericaconnell Let's figure out what we need to do to update this.

**Comment by okwme** [comment]
I see the Dec 10th meeting notes were updated but the subgroup summaries are still missing, right?

**Comment by jandrieu** [comment]
@okwme The summaries are in the repo (including a new update from our last call), but they aren't propagating through the CI/CD system. @deepanshutr  Do you know how to get the build & deploy triggered?

**Comment by deepanshutr** [comment]
The build could be triggered through the actions tab on the repo. But yes the changes seem to not have propagated to the production website. @snj33v if you can pl have a look at the config and update if req.

**Comment by deepanshutr** [comment]
The Build was failing because of missing <li> closing tags. Fixed in https://github.com/interNFT/documentation/pull/26. Added build checks on raising PR.

**Comment by deepanshutr** [comment]
Slides and meeting video links still to be added.
